version: "3"

services:
    camera:
        build: ./camera
        image: photobooth-camera
        container_name: photobooth-camera
        environment:
            - REDIS_HOST=redis
        links:
            - redis
        devices:
            - "/dev/video0:/dev/video0"

    web-server:
        build: ./web
        image: photobooth-web
        container_name: photobooth-web
        ports:
            - 8000:80
        environment:
            - REDIS_HOST=redis
        links:
            - redis
        volumes:
            - photos:/photos
    redis:
        image: redis
        ports:
            - 6379:6379
    app:
        image: photobooth-app
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        ports:
            - 1337:80

volumes:
    photos:
